# REAL
application: emojiworldbot
version: 'v0-95'

# TEST
#application: emojiworlddevbot
#version: 'v0-95'

runtime: python27
api_version: 1
threadsafe: true

#https://cloud.google.com/appengine/docs/python/config/appconfig#scaling_and_instance_types
#https://cloud.google.com/appengine/docs/python/modules/

instance_class: B1
basic_scaling:
  max_instances: 1
  idle_timeout: 5m


#inbound_services:
#- channel_presence

builtins:
- remote_api: on
- deferred: on

handlers:
- url: /set_webhook
  login: admin
  script: main.app

- url: /get_webhook_info
  login: admin
  script: main.app

- url: /delete_webhook
  login: admin
  script: main.app

- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin


#- url: /_ah/channel/connected/
#  script: com.pickmeup-telegram.server.channel.ChannelConnected
#  name: ChannelConnected
#  script: main.app

#- url: /_ah/channel/disconnected/
#  script: com.pickmeup-telegram.server.channel.ChannelDisconnected
#  name: ChannelDisconnected
#  script: main.app

- url: .*
  script: main.app

- url: /EmojiData
  static_dir: EmojiData
  application_readable: true


libraries:
- name: webapp2
  version: latest
- name: PIL
  version: latest
- name: ssl
  version: latest



