# -*- coding: utf-8 -*-

MAX_EMOJI_FOR_ANNOTATION_PER_PERSON_PER_LANGUAGE = 500
MAX_NUMBER_OF_ALREADY_KNOWN_EMOJI_IN_A_ROW = 5
MAX_ANNOTATORS_PER_PRIORITIZED_EMOJI = 5
MIN_COUNT_FOR_USER_TAG_TO_BE_PUBLIC = 2
MAX_NUMBER_OF_DISPLAYED_TAGS_ALTERNATIVE = 3
ADD_TEXT_TO_EMOJI_IN_INLINE_QUERY = True
ADD_LANGUAGE_TO_TEXT_IN_INLINE_QUERY = False and ADD_TEXT_TO_EMOJI_IN_INLINE_QUERY

COUNT_CONSECUTIVE_UPPER_WORDS_BEFORE_MESSAGE = 3