# -*- coding: utf-8 -*-

MAX_EMOJI_FOR_ANNOTATION_PER_PERSON_PER_LANGUAGE = 500
MAX_NUMBER_OF_ALREADY_KNOWN_EMOJI_IN_A_ROW = 3
MAX_ANNOTATORS_PER_PRIORITIZED_EMOJI = 5
MIN_COUNT_FOR_TAGS_SUGGESTED_BY_OTHER_USERS = 2